name: 'chocolatine'
run-name: ${{ github.actor }} checking if avaible to push
on:
  push:
    branches-ignore:
    - 'ga-ignore-'
  pull_request:
    branches-ignore:
    - 'ga-ignore-'

jobs:

  check_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker:latest
    steps:

      - name: use_checkout
        uses: actions/checkout@v3
        with:
          repository: ''

      - name: compile_all_files
        run: make

      - name: clean_files
        run: make clean

      - name: run_files
        run: |
          for file in ${{ vars.EXECUTABLES }}; do
            if [ ! -x "$file" ]; then
              echo "File $file does not exist or is not executable"
              exit 1
            fi
          done

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    if: github.event_name == 'push'
    steps:

      - name: use_checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: push_to_miror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SECRET_KEY_CHOCOLATINE }}